spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://root:root@localhost:27017/depositOptimization?authSource=admin
      database: depositOptimization
  thymeleaf:
    check-template-location: false